global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'funding-rate-arbitrage'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['funding-arbitrage:8000']
